import { TestsDataType } from "./components/TestTemplate/types";

export const christmasMovies = [
  {
    name: "Happiest Season",
    genre: "Romantic Comedy",
    country: "USA",
    year: 2020,
  },
  {
    name: "A California Christmas",
    genre: "Romantic Comedy",
    country: "USA",
    year: 2020,
  },
  {
    name: "The Christmas Chronicles 2",
    genre: "Adventure",
    country: "USA",
    year: 2020,
  },
  {
    name: "Jingle Jangle: A Christmas Journey",
    genre: "Musical",
    country: "USA",
    year: 2020,
  },
  {
    name: "A Boy Called Christmas",
    genre: "Fantasy",
    country: "UK",
    year: 2021,
  },
  {
    name: "The Princess Switch 3: Romancing the Star",
    genre: "Romantic Comedy",
    country: "USA",
    year: 2021,
  },
  { name: "8-Bit Christmas", genre: "Comedy", country: "USA", year: 2021 },
  {
    name: "Single All the Way",
    genre: "Romantic Comedy",
    country: "USA",
    year: 2021,
  },
  {
    name: "A Castle for Christmas",
    genre: "Romantic Comedy",
    country: "USA",
    year: 2021,
  },
  { name: "Love Hard", genre: "Romantic Comedy", country: "USA", year: 2021 },
  {
    name: "The Christmas Chronicles 3",
    genre: "Adventure",
    country: "USA",
    year: 2022,
  },
  {
    name: "Falling for Christmas",
    genre: "Romantic Comedy",
    country: "USA",
    year: 2022,
  },
  {
    name: "The Noel Diary",
    genre: "Romantic Drama",
    country: "USA",
    year: 2022,
  },
  { name: "Spirited", genre: "Musical", country: "USA", year: 2022 },
  {
    name: "Your Christmas or Mine?",
    genre: "Romantic Comedy",
    country: "UK",
    year: 2022,
  },
  {
    name: "Christmas with You",
    genre: "Romantic Comedy",
    country: "USA",
    year: 2022,
  },
  {
    name: "The Guardians of the Galaxy Holiday Special",
    genre: "Action",
    country: "USA",
    year: 2022,
  },
  {
    name: "Christmas Bloody Christmas",
    genre: "Horror",
    country: "USA",
    year: 2022,
  },
  {
    name: "Scrooge: A Christmas Carol",
    genre: "Animation",
    country: "UK",
    year: 2022,
  },
  {
    name: "Klaus: The Holiday Film",
    genre: "Animation",
    country: "Spain",
    year: 2022,
  },
  { name: "Home Alone", genre: "Comedy", country: "USA", year: 1990 },
  {
    name: "Love Actually",
    genre: "Romantic Comedy",
    country: "UK",
    year: 2003,
  },
  { name: "Elf", genre: "Comedy", country: "USA", year: 2003 },
  { name: "The Polar Express", genre: "Animation", country: "USA", year: 2004 },
  { name: "A Christmas Carol", genre: "Animation", country: "USA", year: 2009 },
  { name: "The Grinch", genre: "Comedy", country: "USA", year: 2018 },
  { name: "Die Hard", genre: "Action", country: "USA", year: 1988 },
  {
    name: "The Nightmare Before Christmas",
    genre: "Animation",
    country: "USA",
    year: 1993,
  },
  { name: "The Santa Clause", genre: "Comedy", country: "USA", year: 1994 },
  {
    name: "How the Grinch Stole Christmas",
    genre: "Comedy",
    country: "USA",
    year: 2000,
  },
  {
    name: "A Charlie Brown Christmas",
    genre: "Animation",
    country: "USA",
    year: 1965,
  },
  {
    name: "The Muppets Christmas Carol",
    genre: "Comedy",
    country: "USA",
    year: 1992,
  },
  {
    name: "National Lampoon's Christmas Vacation",
    genre: "Comedy",
    country: "USA",
    year: 1989,
  },
  { name: "It's a Wonderful Life", genre: "Drama", country: "USA", year: 1946 },
  {
    name: "Miracle on 34th Street",
    genre: "Comedy",
    country: "USA",
    year: 1947,
  },
  { name: "White Christmas", genre: "Musical", country: "USA", year: 1954 },
  { name: "Scrooged", genre: "Comedy", country: "USA", year: 1988 },
  { name: "Bad Santa", genre: "Comedy", country: "USA", year: 2003 },
  { name: "Gremlins", genre: "Comedy", country: "USA", year: 1984 },
  { name: "Arthur Christmas", genre: "Animation", country: "UK", year: 2011 },
  { name: "The Holiday", genre: "Romantic Comedy", country: "USA", year: 2006 },
  {
    name: "The Last Christmas",
    genre: "Romantic Comedy",
    country: "UK",
    year: 2019,
  },
  { name: "Frozen", genre: "Animation", country: "USA", year: 2013 },
  {
    name: "Ralph Breaks the Internet",
    genre: "Animation",
    country: "USA",
    year: 2018,
  },
  {
    name: "Jingle Jangle: A Christmas Journey",
    genre: "Musical",
    country: "USA",
    year: 2020,
  },
  {
    name: "A Christmas Prince",
    genre: "Romantic Comedy",
    country: "USA",
    year: 2017,
  },
  {
    name: "The Princess Switch",
    genre: "Romantic Comedy",
    country: "USA",
    year: 2018,
  },
  { name: "Noelle", genre: "Comedy", country: "USA", year: 2019 },
  { name: "Krampus", genre: "Horror", country: "USA", year: 2015 },
  {
    name: "A Boy Called Christmas",
    genre: "Fantasy",
    country: "UK",
    year: 2021,
  },
  {
    name: "The Christmas Chronicles",
    genre: "Adventure",
    country: "USA",
    year: 2018,
  },
  { name: "The Family Stone", genre: "Comedy", country: "USA", year: 2005 },
  { name: "Deck the Halls", genre: "Comedy", country: "USA", year: 2006 },
  { name: "The Snowman", genre: "Animation", country: "UK", year: 1982 },
  {
    name: "The Grinch Who Stole Christmas",
    genre: "Animation",
    country: "USA",
    year: 1966,
  },
  { name: "Frozen II", genre: "Animation", country: "USA", year: 2019 },
  {
    name: "The Nutcracker and the Four Realms",
    genre: "Fantasy",
    country: "USA",
    year: 2018,
  },
  {
    name: "The Christmas Spirit",
    genre: "Comedy",
    country: "Canada",
    year: 2013,
  },
];

export const predictions = [
  "{recipient}, you will find unexpected joy in the simplest of things this year.",
  "This year, {recipient} will discover new passions that will spark excitement every day.",
  "Your energy will radiate, {recipient}, and people will be drawn to your positive vibes.",
  "{recipient}, prepare for new beginnings and exciting opportunities on the horizon.",
  "2025 will be the year of growth and success for you, {recipient}!",
  "A surprise adventure is waiting for you, {recipient}. Embrace the journey.",
  "{recipient}, this year will bring clarity and answers to questions you've been asking.",
  "Romance is in the air, {recipient}. Keep your heart open to new connections.",
  "This year, {recipient} will find balance in their life and feel more grounded than ever.",
  "Expect the unexpected, {recipient}. A twist of fate will bring excitement to your life.",
  "Big changes are coming, {recipient}, but don’t worry—they’re for the better.",
  "{recipient}, trust your instincts. They will guide you towards something amazing.",
  "2025 will be filled with laughter and new friendships, {recipient}. Enjoy every moment.",
  "This is the year, {recipient}, that you’ll step out of your comfort zone and thrive.",
  "{recipient}, your hard work will pay off, and rewards will come your way soon.",
  "Adventure is calling, {recipient}. Get ready to take some bold steps!",
  "{recipient}, you’ll discover a hidden talent that will bring you joy and pride.",
  "2025 will bring clarity to {recipient}'s goals and purpose in life.",
  "{recipient}, someone from your past will reappear with exciting news.",
  "Prepare for unexpected blessings, {recipient}, they’re closer than you think.",
  "Your creativity will flow effortlessly this year, {recipient}. Let your ideas shine.",
  "{recipient}, this year will bring you closer to your dreams than ever before.",
  "Success is within reach, {recipient}. Keep pushing forward, and it will be yours.",
  "{recipient}, keep your eyes open for opportunities that will change your life.",
  "Expect a year of stability and peace, {recipient}. You’ve earned it.",
  "2025 will be a year of great health and wellness for you, {recipient}. Take good care of yourself.",
  "An exciting project will come your way, {recipient}. Don’t hesitate to take it on.",
  "{recipient}, trust your journey. Everything is unfolding exactly as it should.",
  "This year, {recipient} will find joy in the small, everyday moments.",
  "2025 will bring a fresh perspective on life for {recipient}. Embrace the new views.",
  "{recipient}, expect to receive a gift of knowledge that will guide your next steps.",
  "Your relationships will flourish this year, {recipient}. It’s the perfect time for deep connections.",
  "{recipient}, expect to find answers to questions you’ve been pondering for a while.",
  "This year, {recipient} will feel more confident and secure than ever before.",
  "A moment of magic is on its way to {recipient}. Be ready to embrace it.",
  "Trust your heart, {recipient}. It will lead you to the most beautiful experiences this year.",
  "{recipient}, a new chapter is about to begin, filled with exciting possibilities.",
  "This year, {recipient} will make important decisions that will shape their future.",
  "Big changes are on the horizon, {recipient}. Stay prepared for an amazing transformation.",
  "2025 will be the year of personal breakthroughs for {recipient}. Don’t be afraid to shine.",
  "{recipient}, you’ll find strength in places you never thought possible this year.",
  "Expect wonderful surprises, {recipient}. 2025 is full of delightful moments.",
  "{recipient}, new friendships and bonds will make this year unforgettable.",
  "This year will be a journey of self-discovery for {recipient}. Embrace the process.",
  "Don’t hold back, {recipient}. 2025 will bring opportunities that require your courage.",
  "{recipient}, the future is bright! Trust in your abilities, and amazing things will happen.",
  "2025 will be filled with success, {recipient}, but only if you trust your intuition.",
  "{recipient}, expect to receive some exciting news in the coming months.",
  "2025 will be a year of healing for you, {recipient}. Take time for yourself.",
  "This year, {recipient}, your determination will lead you to great achievements.",
  "You’ll be in the right place at the right time this year, {recipient}. Just wait and see.",
  "{recipient}, this year will be full of adventure and new discoveries.",
  "A year of progress and growth awaits you, {recipient}. Stay focused and keep moving forward.",
  "{recipient}, keep your head high—this year will bring wonderful accomplishments.",
  "2025 will bring clarity and purpose to {recipient}. It’s your time to shine.",
  "This year, {recipient} will create lasting memories with loved ones.",
  "Unexpected rewards are coming your way, {recipient}. Get ready to celebrate.",
  "{recipient}, trust your inner wisdom. It will help you navigate any challenges this year.",
  "2025 will be a year of exciting transformations for {recipient}. Embrace the changes.",
  "This year will open doors to new experiences for you, {recipient}. Step through them.",
  "{recipient}, you’ll find yourself surrounded by positivity and good energy in 2025.",
  "Big things are coming for you this year, {recipient}. Keep your focus sharp.",
  "Your creativity will reach new heights this year, {recipient}. Let your ideas take flight.",
  "{recipient}, expect to meet someone new who will change your perspective on life.",
  "2025 will bring a sense of calm and clarity to {recipient}. Enjoy the peaceful moments.",
  "You’re in for a year of surprises, {recipient}. Keep your mind open to the unexpected.",
  "{recipient}, your heart will guide you to the right decisions this year.",
  "2025 will be a year of abundance and prosperity for you, {recipient}. Enjoy the flow.",
  "A year of balance and harmony is coming your way, {recipient}. Embrace the peace.",
  "{recipient}, your resilience will shine through this year. Nothing can stop you.",
  "This year will bring you closer to your true self, {recipient}. Trust the journey.",
  "2025 is the year you’ll achieve something you’ve been dreaming of, {recipient}. Keep working toward it.",
  "This year, {recipient} will find clarity in their relationships and feel more connected than ever.",
  "The universe has big plans for you, {recipient}. Trust the process, and it will all unfold perfectly.",
  "Your ambitions will soar this year, {recipient}. Keep aiming high, and you’ll reach your goals.",
  "{recipient}, you’re about to have a year full of personal victories. Enjoy every moment.",
  "Get ready for a year of self-reflection and growth, {recipient}. It’s time to level up.",
  "{recipient}, your energy will attract success and good fortune in 2025.",
  "Expect a year of new adventures and amazing opportunities, {recipient}. Get ready for the ride.",
  "2025 will be a year of healing for you, {recipient}. Take time to nurture yourself.",
  "{recipient}, your actions this year will lead to rewards beyond your expectations.",
  "A year of balance and well-being awaits you, {recipient}. Stay grounded and healthy.",
  "This year will be full of opportunities, {recipient}. Make sure to seize them.",
  "2025 will bring a sense of accomplishment and pride to {recipient}. Keep going.",
  "{recipient}, expect to discover new places, people, and passions in the coming year.",
  "2025 will be the year of self-love and confidence for {recipient}. Embrace it fully.",
  "{recipient}, this year will bring you closer to achieving your personal goals.",
  "Get ready for a year of abundance and good fortune, {recipient}. It’s your time to shine.",
  "This year, {recipient} will be surrounded by supportive friends and family who lift them up.",
  "2025 is your year, {recipient}. Great things are coming your way.",
  "This year will bring clarity and vision to {recipient}. You’ll see things in a new light.",
  "{recipient}, expect wonderful moments of joy and laughter in 2025.",
  "You’re on the right path, {recipient}. Keep moving forward, and success will follow.",
  "2025 will be filled with incredible experiences for {recipient}. Stay open to them.",
  "You will be guided by wisdom this year, {recipient}. Trust in the process.",
  "{recipient}, a great year filled with accomplishments and joy is ahead of you.",
  "This year, {recipient} will experience a breakthrough in their personal growth.",
  "A new opportunity will present itself to {recipient}, bringing exciting changes",
  "The stars align for {recipient} in matters of love this year.",
  "{recipient} will find clarity in a decision that has been on their mind for months",
  "A creative project will bloom for {recipient} in 2025.",
  "Trust your instincts, {recipient}, they’ll lead you to success.",
  "A surprising twist awaits {recipient} in the next few months.",
  "{recipient} will discover a new hobby that brings them immense joy.",
  "2025 is the year {recipient} takes bold steps toward their dreams.",
  "Someone close to {recipient} will need their advice this year.",
  "A financial opportunity will knock on {recipient}’s door in the near future.",
  "{recipient} will find peace in letting go of what no longer serves them.",
  "Expect a heartfelt reunion with an old friend, {recipient}.",
  "The universe is sending you signs, {recipient}—pay attention to them.",
  "An unexpected adventure will take {recipient} to new horizons this year.",
  "{recipient}’s kindness will return to them tenfold.",
  "This year, {recipient} will overcome a challenge that seemed impossible.",
  "A new chapter is coming for {recipient}—embrace the change.",
  "{recipient} will make a lasting impact on someone’s life.",
  "A long-awaited message will reach {recipient} soon.",
  "A lucky encounter will spark a new relationship for {recipient}.",
  "{recipient} will gain wisdom from an unexpected source this year.",
  "Patience will pay off for {recipient} in their personal life.",
  "A surprise gift will brighten {recipient}’s day before the year ends.",
  "{recipient} will find the courage to speak their truth.",
  "A dream that {recipient} thought was lost will become a reality this year.",
  "This year, {recipient} will embrace a new chapter of their career.",
  "An old challenge will resurface for {recipient}, but they will handle it better this time.",
  "{recipient} will be in the right place at the right time for an exciting opportunity.",
  "A chance to travel will be presented to {recipient}—don’t hesitate!",
  "{recipient} will gain confidence in their own abilities in 2025.",
  "A surprise connection will open doors for {recipient} this year.",
  "{recipient} will finally break free from a limiting situation.",
  "This year, {recipient} will learn something new that changes their perspective.",
  "Love will come knocking at {recipient}’s door unexpectedly.",
  "{recipient} will encounter someone who inspires them to take action.",
  "A big decision looms for {recipient}, but they will make the right choice.",
  "This year, {recipient} will find themselves in the spotlight.",
  "A financial windfall is on the horizon for {recipient}.",
  "{recipient} will reconnect with someone from their past who brings joy.",
  "A change in routine will be refreshing for {recipient} in 2025.",
  "Someone will soon seek {recipient}’s expertise—be ready!",
  "{recipient} will gain new insights that lead to a personal transformation.",
  "The year ahead promises growth and progress for {recipient}.",
  "A long-awaited goal will be within {recipient}’s reach this year.",
  "{recipient} will have the opportunity to be a mentor to someone in need.",
  "This year, {recipient} will take on a challenge and come out stronger.",
  "A new partnership will bring success to {recipient}’s ventures.",
  "{recipient} will be guided toward their true passion this year.",
  "A new friendship will blossom for {recipient}.",
  "This year, {recipient} will find themselves at peace with past decisions.",
  "{recipient} will be presented with a golden opportunity this year.",
  "An unexpected compliment will boost {recipient}’s confidence.",
  "Someone will surprise {recipient} with a thoughtful gesture soon.",
  "{recipient} will gain clarity about a situation that’s been confusing them.",
  "2025 will be the year {recipient} embraces their full potential.",
  "A simple act of kindness from {recipient} will create a ripple effect.",
  "{recipient} will experience an unexpected change in their professional life.",
  "{recipient} will be rewarded for their hard work this year.",
  "A message from the past will resurface, but it will bring closure for {recipient}",
  "{recipient} will take a bold leap of faith that leads to great rewards.",
  "{recipient}’s determination will pay off in unexpected ways this year.",
  "An idea that {recipient} has been mulling over will finally come to fruition.",
  "{recipient} will soon find the answers they’ve been seeking.",
  "A family member will bring good news to {recipient} in the coming months.",
  "{recipient} will discover a new source of inspiration.",
  "The universe is aligning to bring {recipient} closer to their goals.",
  "A financial breakthrough will soon be headed {recipient}’s way.",
  "Someone from {recipient}’s past will come back into their life with good intentions.",
  "{recipient} will soon receive recognition for their hard work.",
  "A special event will make this year unforgettable for {recipient}.",
  "{recipient} will have an enlightening conversation with someone this year.",
  "A breakthrough in a creative project will happen for {recipient}.",
  "A positive change in {recipient}’s personal life is imminent.",
  "{recipient} will feel rejuvenated by the end of the year.",
  "Someone will soon come to {recipient} for guidance and support.",
  "{recipient} will find a way to balance work and personal life more easily.",
  "This year, {recipient} will experience a shift in perspective that brings growth.",
  "{recipient} will be in the right place at the right time for a new opportunity.",
  "A challenge will test {recipient} this year, but they will emerge victorious.",
  "{recipient}’s creativity will be sparked by something unexpected this year.",
  "A new passion project will ignite {recipient}’s enthusiasm.",
  "This year, {recipient} will experience a deep sense of gratitude.",
  "{recipient} will soon meet someone who shares their vision for the future.",
  "An opportunity for travel will soon arise for {recipient}.",
  "{recipient} will take a leap of faith that will lead to personal growth.",
  "This year, {recipient} will learn to trust their intuition more.",
  "Someone will surprise {recipient} with a gesture of kindness.",
  "{recipient} will feel a sense of fulfillment from a job well done.",
  "This year, {recipient} will find the courage to make a major life change.",
  "{recipient} will soon find themselves in a position to help someone in need.",
  "{recipient} will discover a new talent they never knew they had.",
  "A positive shift is coming in {recipient}’s love life this year.",
  "{recipient} will soon experience a feeling of deep inner peace.",
  "Someone will reach out to {recipient} for advice—be prepared!",
  "{recipient} will soon be presented with a decision that will change their life.",
  "{recipient}’s patience will finally pay off in a big way.",
  "A rewarding partnership will form for {recipient} this year.",
  "{recipient} will soon gain the clarity they need to make an important decision.",
  "{recipient} will experience a joyful surprise before the year ends",
];

export const secretSanta = [
  "Jenny",
  "Ira",
  "Diana",
  "Olga",
  "Anastasia",
  "Piter",
  "Jon",
  "Santa",
  "Yana",
  "Bogdan",
  "Nicola",
];

export const tests: TestsDataType = {
  29: {
    title: "Can you ace this quiz? Prove it",
    test: [
      {
        id: "q1",
        question:
          "What is the first step a browser takes when you enter a URL?",
        answers: [
          "Load the page from cache",
          "Send a request to the DNS server",
          "Render the HTML content",
          "Establish a TCP connection",
        ],
      },
      {
        id: "q2",
        question:
          "Which protocol is used to secure communication between a browser and a server?",
        answers: ["HTTP", "FTP", "HTTPS", "SMTP"],
      },
      {
        id: "q3",
        question: "What is the purpose of a DNS server?",
        answers: [
          "To store website content",
          "To map domain names to IP addresses",
          "To establish secure connections",
          "To render HTML and CSS",
        ],
      },
      {
        id: "q4",
        question:
          "What does the browser do when it receives a 404 status code?",
        answers: [
          "Redirects the user to the homepage",
          "Displays a 'Page Not Found' message",
          "Reloads the page",
          "Automatically retries the request",
        ],
      },
      {
        id: "q5",
        question:
          "Which of these HTTP methods is used to retrieve data from a server?",
        answers: ["POST", "DELETE", "PUT", "GET"],
      },
      {
        id: "q6",
        question: "What is the main purpose of cookies?",
        answers: [
          "To store user sessions and preferences",
          "To improve server performance",
          "To optimize image rendering",
          "To serve advertisements",
        ],
      },
      {
        id: "q7",
        question: "What is the critical rendering path?",
        answers: [
          "The process of converting CSS into JavaScript",
          "The sequence of steps the browser takes to render a webpage",
          "The order of HTTP requests",
          "The path of DNS resolution",
        ],
      },
      {
        id: "q8",
        question: "What does 'cache' in a browser do?",
        answers: [
          "Stores frequently used files to speed up loading times",
          "Processes JavaScript faster",
          "Keeps track of user passwords",
          "Runs CSS animations smoothly",
        ],
      },
      {
        id: "q9",
        question: "What is the main function of an SSL certificate?",
        answers: [
          "To validate the server's IP address",
          "To ensure secure communication between client and server",
          "To increase website loading speed",
          "To block spam emails",
        ],
      },
      {
        id: "q10",
        question: "What happens during a TCP handshake?",
        answers: [
          "A secure connection is established using HTTPS",
          "The browser and server exchange packets to establish a connection",
          "The DNS server resolves the domain name",
          "JavaScript code is executed by the browser",
        ],
      },
      {
        id: "q11",
        question: "What does a Content Delivery Network (CDN) do?",
        answers: [
          "Ensures secure communication",
          "Caches and delivers content from servers closer to the user",
          "Handles DNS requests",
          "Optimizes website design",
        ],
      },
      {
        id: "q12",
        question:
          "What does the DOM (Document Object Model) represent in a browser?",
        answers: [
          "The CSS styling structure of a webpage",
          "The HTML structure of a webpage as a tree",
          "The server's response time",
          "The URL routing for a webpage",
        ],
      },
    ],
    correctAnswers: {
      q1: "Send a request to the DNS server",
      q2: "HTTPS",
      q3: "To map domain names to IP addresses",
      q4: "Displays a 'Page Not Found' message",
      q5: "GET",
      q6: "To store user sessions and preferences",
      q7: "The sequence of steps the browser takes to render a webpage",
      q8: "Stores frequently used files to speed up loading times",
      q9: "To ensure secure communication between client and server",
      q10: "The browser and server exchange packets to establish a connection",
      q11: "Caches and delivers content from servers closer to the user",
      q12: "The HTML structure of a webpage as a tree",
    },
  },
  8: {
    title: "How deep is your HTML knowledge? Take the test!",
    test: [
      {
        id: "q1",
        question: "What does the `meta` tag with `name='viewport'` do?",
        answers: [
          "Defines the document's title in the browser",
          "Specifies the character encoding for the document",
          "Controls the page's width and scaling on mobile devices",
          "Preloads critical resources for faster loading",
        ],
      },
      {
        id: "q2",
        question:
          "Which attribute is required in the `<img>` tag to improve accessibility?",
        answers: ["src", "alt", "width", "height"],
      },
      {
        id: "q3",
        question: "What is the purpose of the `role` attribute in HTML?",
        answers: [
          "To define a button's default action",
          "To provide semantic meaning for accessibility tools",
          "To specify the JavaScript behavior of an element",
          "To style elements with CSS",
        ],
      },
      {
        id: "q4",
        question: "What does the `rel` attribute in the `<link>` tag specify?",
        answers: [
          "The URL of the stylesheet",
          "The relationship between the document and the linked resource",
          "The media type of the linked resource",
          "The MIME type of the resource",
        ],
      },
      {
        id: "q5",
        question: "How does the `defer` attribute affect a `<script>` tag?",
        answers: [
          "Executes the script immediately upon parsing",
          "Prevents the script from blocking HTML parsing and executes after the document is parsed",
          "Loads the script only if the user interacts with the page",
          "Loads the script after all images have been loaded",
        ],
      },
      {
        id: "q6",
        question: "What is the difference between `<section>` and `<div>`?",
        answers: [
          "`<section>` adds semantic meaning, `<div>` does not",
          "`<section>` is for styling, `<div>` is for structure",
          "`<section>` is only for headers, `<div>` is for other elements",
          "`<div>` is for semantic grouping, `<section>` is for styling",
        ],
      },
      {
        id: "q7",
        question:
          "What happens when you omit the `action` attribute in a `<form>` tag?",
        answers: [
          "The form data is sent to the current URL",
          "The form data is not submitted",
          "An error is thrown in the console",
          "The browser redirects to the homepage",
        ],
      },
      {
        id: "q8",
        question:
          "Which HTML attribute is used to specify that an input field is mandatory?",
        answers: ["required", "mandatory", "validate", "pattern"],
      },
      {
        id: "q9",
        question: "What does the `<picture>` element do?",
        answers: [
          "Provides multiple sources for an image, allowing for responsive images",
          "Embeds video content on a page",
          "Preloads images for faster rendering",
          "Groups images together in a gallery",
        ],
      },
      {
        id: "q10",
        question: "What is the difference between `<th>` and `<td>`?",
        answers: [
          "`<th>` is for table headers, `<td>` is for table data",
          "`<th>` is used for styling rows, `<td>` is for styling columns",
          "`<td>` contains metadata, `<th>` contains data",
          "`<td>` is nested inside `<tr>`, `<th>` is not",
        ],
      },
      {
        id: "q11",
        question: "Which HTML tag is used for embedding SVG graphics?",
        answers: ["<embed>", "<img>", "<object>", "<svg>"],
      },
      {
        id: "q12",
        question: "Which attribute would you use to open a link in a new tab?",
        answers: [
          "target='_blank'",
          "rel='noopener'",
          "href='_new'",
          "alt='new tab'",
        ],
      },
    ],
    correctAnswers: {
      q1: "Controls the page's width and scaling on mobile devices",
      q2: "alt",
      q3: "To provide semantic meaning for accessibility tools",
      q4: "The relationship between the document and the linked resource",
      q5: "Prevents the script from blocking HTML parsing and executes after the document is parsed",
      q6: "`<section>` adds semantic meaning, `<div>` does not",
      q7: "The form data is sent to the current URL",
      q8: "required",
      q9: "Provides multiple sources for an image, allowing for responsive images",
      q10: "`<th>` is for table headers, `<td>` is for table data",
      q11: "<svg>",
      q12: "target='_blank'",
    },
  },
  15: {
    title: "The ultimate CSS quiz: Beginner or master?",
    test: [
      {
        id: "q1",
        question: "What does the `z-index` property do?",
        answers: [
          "Specifies the opacity of an element",
          "Defines the stacking order of elements",
          "Sets the zoom level of an element",
          "Aligns an element to the center of its container",
        ],
      },
      {
        id: "q2",
        question:
          "Which CSS property is used to make an element's children inherit the parent's grid layout?",
        answers: ["display", "grid-template", "inherit", "grid"],
      },
      {
        id: "q3",
        question:
          "What is the difference between `relative` and `absolute` positioning in CSS?",
        answers: [
          "`relative` positions an element relative to its normal flow, `absolute` positions it relative to its nearest positioned ancestor",
          "`relative` keeps an element in the document flow, `absolute` removes it entirely",
          "`relative` requires a `z-index`, `absolute` does not",
          "`relative` is for inline elements, `absolute` is for block elements",
        ],
      },
      {
        id: "q4",
        question:
          "Which pseudo-class targets an element only when the mouse hovers over it?",
        answers: [":hover", ":focus", ":active", ":visited"],
      },
      {
        id: "q5",
        question: "What does the `flex-grow` property do in a Flexbox layout?",
        answers: [
          "Determines the initial size of the element",
          "Specifies the ability of an element to grow if necessary",
          "Prevents the element from shrinking",
          "Aligns the element along the main axis",
        ],
      },
      {
        id: "q6",
        question:
          "Which of the following is NOT a valid value for the `position` property?",
        answers: ["relative", "absolute", "sticky", "inline"],
      },
      {
        id: "q7",
        question: "What is the difference between `em` and `rem` units?",
        answers: [
          "`em` is relative to the parent element's font size, `rem` is relative to the root element's font size",
          "`em` is for block elements, `rem` is for inline elements",
          "`em` requires a media query, `rem` does not",
          "`em` is for pixels, `rem` is for percentages",
        ],
      },
      {
        id: "q8",
        question:
          "How can you apply styles only when the viewport is less than 768px wide?",
        answers: [
          "@media (max-width: 768px) { ... }",
          "@viewport { max-width: 768px; }",
          "@media (viewport-width < 768px) { ... }",
          "viewport(max-width: 768px) { ... }",
        ],
      },
      {
        id: "q9",
        question:
          "What does the `content` property do in a `::before` or `::after` pseudo-element?",
        answers: [
          "Sets the text or content to be inserted",
          "Controls the visibility of the element",
          "Defines the text alignment",
          "Specifies the z-index of the pseudo-element",
        ],
      },
      {
        id: "q10",
        question: "What is the default value of the `overflow` property?",
        answers: ["visible", "hidden", "scroll", "auto"],
      },
      {
        id: "q11",
        question:
          "Which property allows you to specify how an element is resized in a Flexbox layout?",
        answers: ["flex-basis", "resize", "align-content", "overflow"],
      },
      {
        id: "q12",
        question:
          "How do you create a CSS variable and apply it to an element?",
        answers: [
          "Define with `--var-name: value;` and use with `var(--var-name)`",
          "Define with `$var-name: value;` and use with `$var-name`",
          "Define with `var-name: value;` and use with `--var-name`",
          "Define with `@var-name: value;` and use with `@var-name`",
        ],
      },
    ],
    correctAnswers: {
      q1: "Defines the stacking order of elements",
      q2: "display",
      q3: "`relative` positions an element relative to its normal flow, `absolute` positions it relative to its nearest positioned ancestor",
      q4: ":hover",
      q5: "Specifies the ability of an element to grow if necessary",
      q6: "inline",
      q7: "`em` is relative to the parent element's font size, `rem` is relative to the root element's font size",
      q8: "@media (max-width: 768px) { ... }",
      q9: "Sets the text or content to be inserted",
      q10: "visible",
      q11: "flex-basis",
      q12: "Define with `--var-name: value;` and use with `var(--var-name)`",
    },
  },
  22: {
    title: "Test your skills: Do you really know JavaScript inside out?",
    test: [
      {
        id: "q1",
        question:
          "What is the difference between `==` and `===` in JavaScript?",
        answers: [
          "`==` compares values only, `===` compares both values and types",
          "`==` is used for strings, `===` is used for numbers",
          "`==` performs strict equality, `===` performs loose equality",
          "There is no difference between them",
        ],
      },
      {
        id: "q2",
        question: "What will `typeof null` return?",
        answers: ["'null'", "'undefined'", "'object'", "'boolean'"],
      },
      {
        id: "q3",
        question: "What does `Object.freeze()` do in JavaScript?",
        answers: [
          "Makes an object immutable, preventing addition, deletion, or modification of properties",
          "Deletes all properties of an object",
          "Converts an object into an array",
          "Freezes the memory allocated to an object",
        ],
      },
      {
        id: "q4",
        question: "What is a closure in JavaScript?",
        answers: [
          "A function that remembers the scope in which it was created, even after that scope is destroyed",
          "A way to close all functions within a scope",
          "A mechanism to execute asynchronous code",
          "A special function used only in object-oriented programming",
        ],
      },
      {
        id: "q5",
        question:
          "Which of the following is NOT a valid way to declare a variable?",
        answers: ["var", "let", "const", "define"],
      },
      {
        id: "q6",
        question: "What is the purpose of the `async` keyword in JavaScript?",
        answers: [
          "To define a function that always returns a promise",
          "To execute a function immediately",
          "To pause the execution of a function",
          "To declare a function as synchronous",
        ],
      },
      {
        id: "q7",
        question:
          "What will be logged to the console? \n\n```js\nconst a = [1, 2, 3];\nconst b = a;\nb.push(4);\nconsole.log(a);\n```",
        answers: ["[1, 2, 3]", "[1, 2, 3, 4]", "undefined", "Error"],
      },
      {
        id: "q8",
        question:
          "What is the output of: \n\n```js\nconsole.log([] + []);\n```",
        answers: ["'' (empty string)", "undefined", "0", "Error"],
      },
      {
        id: "q9",
        question: "What does the `bind` method do in JavaScript?",
        answers: [
          "Creates a new function with a specific `this` context",
          "Executes a function immediately",
          "Creates a copy of an object",
          "Binds an object to an array",
        ],
      },
      {
        id: "q10",
        question:
          "Which of the following methods can be used to iterate over an array?",
        answers: [
          "map(), filter(), reduce()",
          "forEach(), map(), splice()",
          "reduce(), pop(), for()",
          "push(), shift(), slice()",
        ],
      },
      {
        id: "q11",
        question:
          "What is the difference between function declarations and function expressions?",
        answers: [
          "Declarations are hoisted, expressions are not",
          "Expressions are hoisted, declarations are not",
          "Expressions can only be anonymous",
          "Declarations can only be used within objects",
        ],
      },
      {
        id: "q12",
        question:
          "What is the purpose of the `setTimeout` function in JavaScript?",
        answers: [
          "To execute a function after a specified delay",
          "To run a function only once",
          "To pause code execution",
          "To call a function at regular intervals",
        ],
      },
    ],
    correctAnswers: {
      q1: "`==` compares values only, `===` compares both values and types",
      q2: "'object'",
      q3: "Makes an object immutable, preventing addition, deletion, or modification of properties",
      q4: "A function that remembers the scope in which it was created, even after that scope is destroyed",
      q5: "define",
      q6: "To define a function that always returns a promise",
      q7: "[1, 2, 3, 4]",
      q8: "'' (empty string)",
      q9: "Creates a new function with a specific `this` context",
      q10: "map(), filter(), reduce()",
      q11: "Declarations are hoisted, expressions are not",
      q12: "To execute a function after a specified delay",
    },
  },
};
