export const christmasMovies = [
  {
    name: "Happiest Season",
    genre: "Romantic Comedy",
    country: "USA",
    year: 2020,
  },
  {
    name: "A California Christmas",
    genre: "Romantic Comedy",
    country: "USA",
    year: 2020,
  },
  {
    name: "The Christmas Chronicles 2",
    genre: "Adventure",
    country: "USA",
    year: 2020,
  },
  {
    name: "Jingle Jangle: A Christmas Journey",
    genre: "Musical",
    country: "USA",
    year: 2020,
  },
  {
    name: "A Boy Called Christmas",
    genre: "Fantasy",
    country: "UK",
    year: 2021,
  },
  {
    name: "The Princess Switch 3: Romancing the Star",
    genre: "Romantic Comedy",
    country: "USA",
    year: 2021,
  },
  { name: "8-Bit Christmas", genre: "Comedy", country: "USA", year: 2021 },
  {
    name: "Single All the Way",
    genre: "Romantic Comedy",
    country: "USA",
    year: 2021,
  },
  {
    name: "A Castle for Christmas",
    genre: "Romantic Comedy",
    country: "USA",
    year: 2021,
  },
  { name: "Love Hard", genre: "Romantic Comedy", country: "USA", year: 2021 },
  {
    name: "The Christmas Chronicles 3",
    genre: "Adventure",
    country: "USA",
    year: 2022,
  },
  {
    name: "Falling for Christmas",
    genre: "Romantic Comedy",
    country: "USA",
    year: 2022,
  },
  {
    name: "The Noel Diary",
    genre: "Romantic Drama",
    country: "USA",
    year: 2022,
  },
  { name: "Spirited", genre: "Musical", country: "USA", year: 2022 },
  {
    name: "Your Christmas or Mine?",
    genre: "Romantic Comedy",
    country: "UK",
    year: 2022,
  },
  {
    name: "Christmas with You",
    genre: "Romantic Comedy",
    country: "USA",
    year: 2022,
  },
  {
    name: "The Guardians of the Galaxy Holiday Special",
    genre: "Action",
    country: "USA",
    year: 2022,
  },
  {
    name: "Christmas Bloody Christmas",
    genre: "Horror",
    country: "USA",
    year: 2022,
  },
  {
    name: "Scrooge: A Christmas Carol",
    genre: "Animation",
    country: "UK",
    year: 2022,
  },
  {
    name: "Klaus: The Holiday Film",
    genre: "Animation",
    country: "Spain",
    year: 2022,
  },
  { name: "Home Alone", genre: "Comedy", country: "USA", year: 1990 },
  {
    name: "Love Actually",
    genre: "Romantic Comedy",
    country: "UK",
    year: 2003,
  },
  { name: "Elf", genre: "Comedy", country: "USA", year: 2003 },
  { name: "The Polar Express", genre: "Animation", country: "USA", year: 2004 },
  { name: "A Christmas Carol", genre: "Animation", country: "USA", year: 2009 },
  { name: "The Grinch", genre: "Comedy", country: "USA", year: 2018 },
  { name: "Die Hard", genre: "Action", country: "USA", year: 1988 },
  {
    name: "The Nightmare Before Christmas",
    genre: "Animation",
    country: "USA",
    year: 1993,
  },
  { name: "The Santa Clause", genre: "Comedy", country: "USA", year: 1994 },
  {
    name: "How the Grinch Stole Christmas",
    genre: "Comedy",
    country: "USA",
    year: 2000,
  },
  {
    name: "A Charlie Brown Christmas",
    genre: "Animation",
    country: "USA",
    year: 1965,
  },
  {
    name: "The Muppets Christmas Carol",
    genre: "Comedy",
    country: "USA",
    year: 1992,
  },
  {
    name: "National Lampoon's Christmas Vacation",
    genre: "Comedy",
    country: "USA",
    year: 1989,
  },
  { name: "It's a Wonderful Life", genre: "Drama", country: "USA", year: 1946 },
  {
    name: "Miracle on 34th Street",
    genre: "Comedy",
    country: "USA",
    year: 1947,
  },
  { name: "White Christmas", genre: "Musical", country: "USA", year: 1954 },
  { name: "Scrooged", genre: "Comedy", country: "USA", year: 1988 },
  { name: "Bad Santa", genre: "Comedy", country: "USA", year: 2003 },
  { name: "Gremlins", genre: "Comedy", country: "USA", year: 1984 },
  { name: "Arthur Christmas", genre: "Animation", country: "UK", year: 2011 },
  { name: "The Holiday", genre: "Romantic Comedy", country: "USA", year: 2006 },
  {
    name: "The Last Christmas",
    genre: "Romantic Comedy",
    country: "UK",
    year: 2019,
  },
  { name: "Frozen", genre: "Animation", country: "USA", year: 2013 },
  {
    name: "Ralph Breaks the Internet",
    genre: "Animation",
    country: "USA",
    year: 2018,
  },
  {
    name: "Jingle Jangle: A Christmas Journey",
    genre: "Musical",
    country: "USA",
    year: 2020,
  },
  {
    name: "A Christmas Prince",
    genre: "Romantic Comedy",
    country: "USA",
    year: 2017,
  },
  {
    name: "The Princess Switch",
    genre: "Romantic Comedy",
    country: "USA",
    year: 2018,
  },
  { name: "Noelle", genre: "Comedy", country: "USA", year: 2019 },
  { name: "Krampus", genre: "Horror", country: "USA", year: 2015 },
  {
    name: "A Boy Called Christmas",
    genre: "Fantasy",
    country: "UK",
    year: 2021,
  },
  {
    name: "The Christmas Chronicles",
    genre: "Adventure",
    country: "USA",
    year: 2018,
  },
  { name: "The Family Stone", genre: "Comedy", country: "USA", year: 2005 },
  { name: "Deck the Halls", genre: "Comedy", country: "USA", year: 2006 },
  { name: "The Snowman", genre: "Animation", country: "UK", year: 1982 },
  {
    name: "The Grinch Who Stole Christmas",
    genre: "Animation",
    country: "USA",
    year: 1966,
  },
  { name: "Frozen II", genre: "Animation", country: "USA", year: 2019 },
  {
    name: "The Nutcracker and the Four Realms",
    genre: "Fantasy",
    country: "USA",
    year: 2018,
  },
  {
    name: "The Christmas Spirit",
    genre: "Comedy",
    country: "Canada",
    year: 2013,
  },
];
